name: Node.js CI

on:
  push:
    branches: ["main", "unit-tests"]
  pull_request:
    branches: ["main", "unit-tests"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Change permissions for test files
        run: sudo chmod -R 755 tests/
      - name: Perform Mocha Tests
        run: npm test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HANDLE: ${{ secrets.HANDLE }}
          URL: ${{ secrets.URL }}
